spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleact?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: iron
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


